# Laboratory 8 : System of Linear Equations <br>
Coded and Submitted By:<br>
Ricafrente, Ric Jhon Dayle D<br>
201813672<br>
58011

In [27]:
import numpy as np
import matplotlib.pyplot as plt
import math
%matplotlib inline


The cost of admission to a popular music concert was 162 dollars for 12 children and 3 adults. The admission was 122 dollars for 8 children and 3 adults in another music concert. How much was the admission for each child and adult?
$$\begin{bmatrix} 3a + 12c\\ 3a + 8c \end{bmatrix}\cdot\begin{bmatrix}a\\c\end{bmatrix} = \begin{bmatrix}162\\122\end{bmatrix} $$


In [28]:
people = np.array([
    [3, 12],
    [3, 8]
])
cost = np.array([
    [162],
    [122]
])
print (people)
print (people.shape)
print (cost)
print (cost.shape)


[[ 3 12]
 [ 3  8]]
(2, 2)
[[162]
 [122]]
(2, 1)


In [35]:
prices = np.linalg.inv(people) @ cost  
print('The cost of admission per adult is: ${:.2f}'.format(float(prices[0])))
print('The cost of admission per child is: ${:.2f}'.format(float(prices[1])))


The cost of admission per adult is: $14.00
The cost of admission per child is: $10.00


In [30]:
population_inv = np.linalg.inv(population)
population_inv

array([[-0.66666667,  1.        ],
       [ 0.25      , -0.25      ]])

In [32]:
r = population_inv @ cost
r

array([[14.],
       [10.]])

In [ ]:
Y_1 = population @ r
np.array_equal(Y_1, cost)

In [16]:
population_sol = np.linalg.solve(people,cost)
population_sol

array([[14.],
       [10.]])